services:
  - type: web
    name: puppeteer-service
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      PUPPETEER_CACHE_DIR: /opt/render/.cache/puppeteer
    disk:
      name: puppeteer-cache
      mountPath: /opt/render/.cache/puppeteer
      sizeGB: 1
