services:
  - type: web
    name: puppeteer-service
    env: node
    buildCommand: npm install
    startCommand: node server.js
    disk:
      name: puppeteer-cache
      mountPath: /opt/render/.cache/puppeteer
      sizeGB: 1
